### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by MustafaMC8** [TheNoobInventor/lidarbot#1]
Hi, your project is so nice, I wanna make it but in my country motor drive hat doesn't available. Can you write code for l298n motor drive instead of motor drive hat.thanks

**Comment by TheNoobInventor** [comment]
Hello Mustafa, thank you for the interest in the project. Unfortunately I cannot help you with your request. I have not used an L298N motor driver before, the Motor Driver HAT is the first driver I've worked with. 

But have you tried checking out videos by Articulated Robotics? Josh uses the L298N for his differential drive robot. Here are some of his links that might help put:

https://articulatedrobotics.xyz/mobile-robot-1-project-overview/

https://www.youtube.com/watch?v=-PCuDnpgiew

https://www.youtube.com/watch?v=OWeLUSzxMsw

I hope these help you with what you are working on.

**Comment by MustafaMC8** [comment]
OK,thanks

**Comment by TheNoobInventor** [comment]
You are welcome!
