### ISSUE TITLE
Pacakge rplidar_ros not found error

### ISSUE THREAD

**Issue by HARSHGURU** [TheNoobInventor/lidarbot#10]
```bash
ros2 launch lidarbot_bringup lidarbot_bringup_launch.py use_robot_localization:=false
```

After giving above command in terminal it throw an error: Caught exception in launch package rplidar_ros not found

**Comment by TheNoobInventor** [comment]
Hi, 

It looks the `rplidar_ros` package isn't installed. Try running this command:

```
sudo apt install ros-humble-rplidar-ros
```

Then execute the launch command again. I am curious, did you try running the launch command on the robot or on your computer?

**Comment by HARSHGURU** [comment]
Yes dude it's work. Thanks a lot 🤩
