### ISSUE TITLE
package controller_manager not found error

### ISSUE THREAD

**Issue by HARSHGURU** [TheNoobInventor/lidarbot#11]
```
ros2 launch lidarbot_bringup lidarbot_bringup_launch.py
```
After running above command I got error controller_manager package not found

**Comment by HARSHGURU** [comment]
Yes the above error was solve but the problem is that while running command 
```rviz2 -d src/lidarbot_slam/rviz/lidarbot_slam.rviz```
I got the new error on my development machine i.e.
```X11 connection rejected because of wrong authentication.
qt.qpa.xcb: could not connect to display localhost:11.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.```

**Comment by TheNoobInventor** [comment]
I haven't come across this error before, but it seems like it might a problem with the QT software install. To confirm this, try opening rviz on its own in the terminal with: 
```
rviz2
```
