### ISSUE TITLE
Lidar Description not found 

### ISSUE THREAD

**Issue by sahilsaqi** [TheNoobInventor/lidarbot#4]
after installing the Docs / Gazebo Harmonic https://gazebosim.org/docs/harmonic/install_ubuntu

then i run the commmand ros2 launch lidarbot_description description_launch.py
and i got Error like Package 'lidar_description not found' 
![Screenshot 2024-01-11 115544](https://github.com/TheNoobInventor/lidarbot/assets/85507172/3d8d7230-6fd0-4836-9172-7581d00e976a)

**Comment by TheNoobInventor** [comment]
Hello Saqi, 

I used [Gazebo classic](https://classic.gazebosim.org/tutorials?tut=install_ubuntu&cat=install) for this project and not the newer Gazebo version, I believe that's the reason for the error. I am yet to use the newer versions so I cannot make any suggestions on integrations.
