### ISSUE TITLE
Unable to locate package ros-humble-gazebo-ros2-control

### ISSUE THREAD

**Issue by sahilsaqi** [TheNoobInventor/lidarbot#5]
After going through step by step process i finallu ran this command 
"rosdep install --from-paths src --ignore-src --rosdistro humble -r -y"

and i got this error 
aiot@ubuntu:~/ros2_ws$ rosdep install --from-paths src --ignore-src --rosdistro humble -r -y
executing command [sudo -H apt-get install -y ros-humble-gazebo-ros2-control]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package ros-humble-gazebo-ros2-control
executing command [sudo -H apt-get install -y ros-humble-gazebo-ros-pkgs]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package ros-humble-gazebo-ros-pkgs
ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install -y ros-humble-gazebo-ros2-control] failed
  apt: command [sudo -H apt-get install -y ros-humble-gazebo-ros-pkgs] failed
  apt: Failed to detect successful installation of [ros-humble-gazebo-ros2-control]
  apt: Failed to detect successful installation of [ros-humble-gazebo-ros-pkgs]

**Comment by TheNoobInventor** [comment]
Hello, 

I just want to confirm this, did you run the command on your development machine/PC or on your robot?

**Comment by sahilsaqi** [comment]
Machine

**Comment by oscarlov** [comment]
> After going through step by step process i finallu ran this command "rosdep install --from-paths src --ignore-src --rosdistro humble -r -y"
> 
> and i got this error aiot@ubuntu:~/ros2_ws$ rosdep install --from-paths src --ignore-src --rosdistro humble -r -y executing command [sudo -H apt-get install -y ros-humble-gazebo-ros2-control] Reading package lists... Done Building dependency tree... Done Reading state information... Done E: Unable to locate package ros-humble-gazebo-ros2-control executing command [sudo -H apt-get install -y ros-humble-gazebo-ros-pkgs] Reading package lists... Done Building dependency tree... Done Reading state information... Done E: Unable to locate package ros-humble-gazebo-ros-pkgs ERROR: the following rosdeps failed to install apt: command [sudo -H apt-get install -y ros-humble-gazebo-ros2-control] failed apt: command [sudo -H apt-get install -y ros-humble-gazebo-ros-pkgs] failed apt: Failed to detect successful installation of [ros-humble-gazebo-ros2-control] apt: Failed to detect successful installation of [ros-humble-gazebo-ros-pkgs]

did you have an answer? because I have the same problem and I can't solve it.

**Comment by sahilsaqi** [comment]
> > After going through step by step process i finallu ran this command "rosdep install --from-paths src --ignore-src --rosdistro humble -r -y"
> > and i got this error aiot@ubuntu:~/ros2_ws$ rosdep install --from-paths src --ignore-src --rosdistro humble -r -y executing command [sudo -H apt-get install -y ros-humble-gazebo-ros2-control] Reading package lists... Done Building dependency tree... Done Reading state information... Done E: Unable to locate package ros-humble-gazebo-ros2-control executing command [sudo -H apt-get install -y ros-humble-gazebo-ros-pkgs] Reading package lists... Done Building dependency tree... Done Reading state information... Done E: Unable to locate package ros-humble-gazebo-ros-pkgs ERROR: the following rosdeps failed to install apt: command [sudo -H apt-get install -y ros-humble-gazebo-ros2-control] failed apt: command [sudo -H apt-get install -y ros-humble-gazebo-ros-pkgs] failed apt: Failed to detect successful installation of [ros-humble-gazebo-ros2-control] apt: Failed to detect successful installation of [ros-humble-gazebo-ros-pkgs]
> 
> did you have an answer? because I have the same problem and I can't solve it.

I recommend you to use ros 1 noetic
