### ISSUE TITLE
Camera for mapping

### ISSUE THREAD

**Issue by D1Vincenzo** [TheNoobInventor/lidarbot#6]
Hi! I am learning multi-sensor fusion related knowledge and just found this amazing project. Can I ask is the camera involved in the mapping, or obstacle avoidance?

**Comment by TheNoobInventor** [comment]
Thank you for the kind words!

As for the camera, it's mainly there for the user to see where the robot is, basically a first person view. 

Mapping and obstacle avoidance are achieved using the RPlidar sensor. Then sensor fusion is carried out on wheel odometry and IMU data to provide more accurate robot odometry estimates. 

I hope this helps to clarify things.

**Comment by D1Vincenzo** [comment]
Got it! Thanks for the reply:)
