### ISSUE TITLE
Gazebo problems

### ISSUE THREAD

**Issue by oscarlov** [TheNoobInventor/lidarbot#8]
Hi I can't install Gazebo Classic or Gazebo 11 with Humble version. How did you do?

**Comment by TheNoobInventor** [comment]
Hi, 

I am only seeing this now. I didn't do anything special, I just followed the steps in here: [Gazebo Classic](https://classic.gazebosim.org/tutorials?tut=install_ubuntu&cat=install). 

Did you follow that as well? What particular issues are you having?

**Comment by TheNoobInventor** [comment]
Okay I'm not sure what's going on but have you tried the alternative way of installing it? If I'm remembering correctly I think I had the same issue installing it from the script. These are the [alternative steps](https://classic.gazebosim.org/tutorials?tut=install_ubuntu&cat=install#Alternativeinstallation:step-by-step).

**Comment by oscarlov** [comment]
If I use the step by step instructions I get the following error after the command: sudo apt-get update
Hit:1 http://ports.ubuntu.com/ubuntu-ports jammy InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease                                
Hit:3 http://ports.ubuntu.com/ubuntu-ports jammy-backports InRelease                              
Hit:4 http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease                               
Hit:5 https://packages.microsoft.com/repos/code stable InRelease                                  
Hit:6 http://packages.osrfoundation.org/gazebo/ubuntu-stable jammy InRelease                      
Ign:7 http://packages.ros.org/ros/ubuntu jammy InRelease                                     
Hit:8 http://packages.ros.org/ros2/ubuntu jammy InRelease
Err:9 http://packages.ros.org/ros/ubuntu jammy Release
  404  Not Found [IP: 2605:bc80:3010::134 80]
Reading package lists... Done
W: http://packages.osrfoundation.org/gazebo/ubuntu-stable/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
E: The repository 'http://packages.ros.org/ros/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Did you use this method to install Gazebo? Because for me it's not working. Thanks for answering me
