### ISSUE TITLE
robot model in RViz flickers during map generation / navigation

### ISSUE THREAD

**Issue by lin-crystal** [TheNoobInventor/lidarbot#9]
Update: problem is solved🥳

Hi Chinedu, thank you for the amazing project and work!!!
I am currently working on a Bachelor thesis project and referring to your project code. For my project, I am using an Arduino robot with a differential drive wheel, the Arduino robot is equipped with a Raspberry PI4 board and a RPLidar laser ranger. ROS2 is running on the Raspberry PI (as ROS2 server), which controls the RPLidar and Arduino. I've implemented a hardware interface between ROS2 and the motor/encoder, as well as a serial communication interface between Raspberry PI and Arduino. On my PC, (as ROS2 client), I am running RViz, Navigation2 and SLAM, a server and client network configuration is also set up. I do not have a camera nor IMU sensor equipped on my robot.

However, I've encountered some issues with RViz during map generation and navigation. 
- map generation: 
When Arduino robot is driven around using a joystick, there is a flickering issue with the robot model in RViz. The lidar map can  be generated (please refer to video: “map_generation_RViz" and “map_generation_robot").
- navigation:
The lidar map saved from map generation is used for navigation. However, the robot model in RViz moves slowly to another position and sometimes jumps to other positions, even though the Arduino robot remains stationary. The workaround for this issue is to re-estimate the position of the robot model in RViz before setting the next navigation goal. After the re-estimation, the Arduino robot will adjust its position and velocity to the according direction, then the next navigation goal can be set (please refer to video: "navigation_RViz" and “navigation_robot").

Here are the videos demonstrating the Arduino robot and RViz (link: https://drive.google.com/drive/folders/1d4ghat_3an8GGp7BKmsZSXNS8OKigj-e?usp=drive_link). 

I am quite new to ROS2 and have been unable to resolve this problem despite trying some troubleshooting methods..... I really wish you could give me some advice and suggestions. Thank you so much and looking forward to your reply!

**Comment by TheNoobInventor** [comment]
Hi Lin, 

I am only just seeing this now, but I am glad to hear that you sorted out the issue. I am curious as to how you fixed it, could also help someone else that could have the issue later on.

Also, thank you for the kind words about the project! And I wish you all the best on your thesis!

**Comment by btajne** [comment]
Hi lin,

I am also going through the same problem . even though i am not moving my robot forward, left ,right, backward then also in the Rviz the robot module is keep on moving and also the map is getting generated . it would be great help to us if you guide us through for solving this issue.

thanks in advance !
